apiVersion: apps/v1
kind: Deployment
metadata:
  name: station-service
  namespace: lastmile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: station-service
  template:
    metadata:
      labels:
        app: station-service
    spec:
      containers:
      - name: station-service
        image: saniyaismail999/lastmile-station:1.0
        env:
        - name: DATABASE_URL
          value: "postgresql://lastmile:lastmile@postgres:5432/lastmile"
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: station-service
  namespace: lastmile
spec:
  selector:
    app: station-service
  ports:
  - port: 50051
    targetPort: 50051
