apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service
  namespace: lastmile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      containers:
      - name: matching-service
        image: saniyaismail999/lastmile-matching:1.0
        env:
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672/"
        - name: TRIP_SERVICE_HOST
          value: "trip-service:50055"
        - name: NOTIFICATION_SERVICE_HOST
          value: "notification-service:50056"
        - name: DEFAULT_SEATS
          valueFrom:
            configMapKeyRef:
              name: lastmile-config
              key: DEFAULT_SEATS
        ports:
        - containerPort: 50054
---
apiVersion: v1
kind: Service
metadata:
  name: matching-service
  namespace: lastmile
spec:
  selector:
    app: matching-service
  ports:
  - port: 50054
    targetPort: 50054
