apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service
  namespace: lastmile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      containers:
      - name: driver-service
        image: saniyaismail999/lastmile-driver:1.0
        env:
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672/"
        ports:
        - containerPort: 50052
---
apiVersion: v1
kind: Service
metadata:
  name: driver-service
  namespace: lastmile
spec:
  selector:
    app: driver-service
  ports:
  - port: 50052
    targetPort: 50052
