apiVersion: v1
kind: Secret
metadata:
  name: lastmile-secrets
  namespace: lastmile
type: Opaque
data:
  POSTGRES_PASSWORD: bGFzdG1pbGU=
  RABBITMQ_DEFAULT_USER: Z3Vlc3Q=
  RABBITMQ_DEFAULT_PASS: Z3Vlc3Q=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: lastmile-config
  namespace: lastmile
data:
  DEFAULT_SEATS: "5"
