apiVersion: apps/v1
kind: Deployment
metadata:
  name: rider-service
  namespace: lastmile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rider-service
  template:
    metadata:
      labels:
        app: rider-service
    spec:
      containers:
      - name: rider-service
        image: saniyaismail999/lastmile-rider:1.0
        env:
        - name: DATABASE_URL
          value: "postgresql://lastmile:lastmile@postgres:5432/lastmile"
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672/"
        ports:
        - containerPort: 50057
---
apiVersion: v1
kind: Service
metadata:
  name: rider-service
  namespace: lastmile
spec:
  selector:
    app: rider-service
  ports:
  - port: 50057
    targetPort: 50057
