apiVersion: v1
kind: Service
metadata:
  name: rider-service
  namespace: lastmile
  labels:
    app: rider-service
spec:
  type: ClusterIP
  selector:
    app: rider-service
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8008
