apiVersion: v1
kind: Service
metadata:
  name: driver-service
  namespace: lastmile
  labels:
    app: driver-service
spec:
  type: ClusterIP
  selector:
    app: driver-service
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
