apiVersion: v1
kind: Service
metadata:
  name: station-service
  namespace: lastmile
  labels:
    app: station-service
spec:
  type: ClusterIP
  selector:
    app: station-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
