apiVersion: v1
kind: Service
metadata:
  name: location-service
  namespace: lastmile
  labels:
    app: location-service
spec:
  type: ClusterIP
  selector:
    app: location-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
